apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ensemblgenomes-ingress
spec:
  rules:
  - host: ensemblgenomes.org
    http:
      paths:
      - backend:
          service: 
            name: ensemblgenomes-svc
            port:
              number: 80
        path: /
        pathType: Prefix 